### ISSUE TITLE
Investigation Evidence

### ISSUE THREAD

**Issue by snaeem3** [guyfleeman/inform7game#16]
Living Room:
couch (probably not evidence)
TV      (probably scenery)
laptop
Ketamine (in couch)

Garage:
hand drill
wrench
screwdriver
hammer
scale

Unknown Location
card
cell phone

**Comment by guyfleeman** [comment]
To Add:

Master Bedroom:
Needle
Vial
Financial Books
Desktop
Zip Tied body

Living Room:
glass shards

Kitchen:
glass shards
ransacked drawers
ransacked cabinets

Back Yard:
Footprints
Door Smashed _in_

Front Yard:
Door Smashed _in_

Child's Room:
Intentionally Clean

**Comment by guyfleeman** [comment]
<name> <pts invst> <pts staging>
<>     <17>        <21>
[living room]
laptop:         3 (i), 3 (i)
glass shards:   2 (i), 2 (i)
ketamine:   2 (u), 2 (u)

[upstairs]
blood streaks:  1 (i), 0 (n)

[back yard]
footprints:     1 (i), 0 (n)
pond/beer:  1 (i), 5 (i)

[garage]
power box:  2 (u), 2 (u)
keyring (see vial/desk) 

[kitchen]
cabinets:       1 (i), 1 (i)
drawers:        1 (i), 1 (i)
glass pieces:   2 (i), 3 (i)

[master bedroom]
body        1 (i), 1 (i)
needle      1 (i), 2 (i)
scale       1 (i), 2 (i)
vial        3 (i), 2 (i)

Key:
(i) implemented
(u) unimplemented
(n) nonimplementable
